package com.myproject.project;


import com.itextpdf.text.pdf.PdfName;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rishi
 */
public class Product extends javax.swing.JFrame {
   
        private String ShopUser;
        private String UserId;
        
        
        
        
        public void setUsername(String username)
        {
//            this.Shop_Name_jLabel.setText(username);
            this.ShopUser = username;
//            Product_Name_TextField.setText(getUsername());
        }
        
       
        public String getUsername()
        {
//            return this.Shop_Name_jLabel.getText();
            return this.ShopUser;

        }
    
  
   
    
    /**
     * Creates new form Product
     */
    public Product() {
        
        
        initComponents();
        
        DisplayProduct();
        
        
        

        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Product_Name_TextField = new javax.swing.JTextField();
        Product_Price_TextField = new javax.swing.JTextField();
        Product_InStock_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Delete_Product_Button = new javax.swing.JButton();
        Edit_Product_Button = new javax.swing.JButton();
        Clear_Button = new javax.swing.JButton();
        Add_Product_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Product_table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Logout_jPanel = new javax.swing.JPanel();
        Logout_jLabel = new javax.swing.JLabel();
        Shop_Name_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setText("Manage Product");

        Product_Price_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_Price_TextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Product Price:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Product In Stock:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Product Name:");

        Delete_Product_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\trash.png")); // NOI18N
        Delete_Product_Button.setText("Delete");
        Delete_Product_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Product_ButtonActionPerformed(evt);
            }
        });

        Edit_Product_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\edit.png")); // NOI18N
        Edit_Product_Button.setText("Edit");
        Edit_Product_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_Product_ButtonActionPerformed(evt);
            }
        });

        Clear_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\clear.png")); // NOI18N
        Clear_Button.setText("Clear");
        Clear_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear_ButtonMouseClicked(evt);
            }
        });

        Add_Product_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\add.png")); // NOI18N
        Add_Product_Button.setText("Add");
        Add_Product_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Product_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("List of current Product");

        Product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Product_table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Product_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Product_InStock_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Add_Product_Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Edit_Product_Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Delete_Product_Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Clear_Button))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Product_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_InStock_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edit_Product_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Product_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_Product_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel7.setText("Shop ");

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\shop.png")); // NOI18N

        Logout_jPanel.setBackground(new java.awt.Color(204, 204, 255));

        Logout_jLabel.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\logout.png")); // NOI18N
        Logout_jLabel.setText("Logout");
        Logout_jLabel.setAlignmentX(0.5F);
        Logout_jLabel.setFocusable(false);
        Logout_jLabel.setIconTextGap(6);
        Logout_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_jLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_jLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_jLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Logout_jPanelLayout = new javax.swing.GroupLayout(Logout_jPanel);
        Logout_jPanel.setLayout(Logout_jPanelLayout);
        Logout_jPanelLayout.setHorizontalGroup(
            Logout_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logout_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );
        Logout_jPanelLayout.setVerticalGroup(
            Logout_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logout_jLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Shop_Name_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Logout_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(Shop_Name_jLabel)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(Shop_Name_jLabel)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
        public void DisplayProduct()
    {
        try
        {
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            
            

            ResultSet rs=st.executeQuery("SELECT Product_Id,Product_Name,Price,In_Stock FROM products p INNER JOIN shops s ON p.Shop_Id = s.Shop_Id WHERE s.Username = '"+ShopUser+"'");
              


            Product_table.setModel(DbUtils.resultSetToTableModel(rs));
//            ResultSet rs2=st.executeQuery("select max(ProductId) from Product ");
//            if(rs2.first())
//            {
//                int id=rs2.getInt(1);
//                id=id+1;
//                String str=String.valueOf(id);
//                Product_Id_jLabel.setText(str);
//            }
//            else
//                Product_Id_jLabel.setText("1");
        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    }
        
    }
    private void Clear_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear_ButtonMouseClicked
        // TODO add your handling code here:
         
        

            Product_Name_TextField.setText("");
            Product_Price_TextField.setText("");
            Product_InStock_TextField.setText("");
            
         
            
        
    }//GEN-LAST:event_Clear_ButtonMouseClicked

    private void Product_Price_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_Price_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_Price_TextFieldActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        try
        {
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            
            ResultSet rs=st.executeQuery("SELECT Product_Id,Product_Name,Price,In_Stock FROM products p INNER JOIN shops s ON p.Shop_Id = s.Shop_Id WHERE s.Username = '"+ShopUser+"'");
            
            
            
            Product_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    }
        
       
    }//GEN-LAST:event_formComponentShown

    private void Product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Product_table.getModel();
        int Myindex=Product_table.getSelectedRow();
//        Product_Id_jLabel.setText(model.getValueAt(Myindex, 0).toString());
        Product_Name_TextField.setText(model.getValueAt(Myindex, 1).toString());
        Product_Price_TextField.setText(model.getValueAt(Myindex, 2).toString());
        Product_InStock_TextField.setText(model.getValueAt(Myindex, 3).toString());

    }//GEN-LAST:event_Product_tableMouseClicked

    private void Add_Product_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Product_ButtonActionPerformed
        // TODO add your handling code here:
        if(Product_Name_TextField.getText().isEmpty()||Product_Price_TextField.getText().isEmpty()||Product_InStock_TextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Missing Data");
        }
        else{       
        String product_name=Product_Name_TextField.getText();
        String product_price=Product_Price_TextField.getText();
        String product_inStock=Product_InStock_TextField.getText();
        try {
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            st.execute("INSERT INTO products(Product_Name,Price,In_Stock,Shop_Id) values('"+product_name+"','"+product_price+"','"+product_inStock+"',"+"(SELECT Shop_Id FROM shops where Username='"+ShopUser+"')"+")");

            JOptionPane.showMessageDialog(null, "Data Sucessfully Inserted");
            con.close();
            DisplayProduct();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Value must be integer");
//                JOptionPane.showMessageDialog(null, e);

        }
        }
    }//GEN-LAST:event_Add_Product_ButtonActionPerformed

    private void Delete_Product_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Product_ButtonActionPerformed
        // TODO add your handling code here:
        if (Product_Name_TextField.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(null, "Select Data to be deleted");
        }
        else{
        DefaultTableModel model = (DefaultTableModel)Product_table.getModel();
        int Myindex=Product_table.getSelectedRow();

        String productid=model.getValueAt(Myindex, 0).toString();


        
        try {
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("delete from Products where Product_Id="+productid);
            JOptionPane.showMessageDialog(null, "Data Sucessfully Deleted");
            con.close();
            DisplayProduct();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_Delete_Product_ButtonActionPerformed

    private void Edit_Product_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_Product_ButtonActionPerformed
        // TODO add your handling code here:
        if(Product_Name_TextField.getText().isEmpty()||Product_Price_TextField.getText().isEmpty()||Product_InStock_TextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Missing Data");
        }
        else{
        DefaultTableModel model = (DefaultTableModel)Product_table.getModel();
        int Myindex=Product_table.getSelectedRow();
        String productid=model.getValueAt(Myindex, 0).toString();
        String product_name=Product_Name_TextField.getText();
        String product_price=Product_Price_TextField.getText();
        String product_inStock=Product_InStock_TextField.getText();
        try {
            
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("update Products set Product_Name='"+product_name+"'"+",Price='"+product_price+"'"+",In_Stock='"+product_inStock+"'"+" where Product_Id="+productid);
            JOptionPane.showMessageDialog(null, "Data Sucessfully Updated");
            con.close();
            DisplayProduct();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Value must be integer");
        }
        }
    }//GEN-LAST:event_Edit_Product_ButtonActionPerformed

    private void Logout_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_jLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_Logout_jLabelMouseClicked

    private void Logout_jLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_jLabelMouseEntered
        // TODO add your handling code here:
        Logout_jLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_Logout_jLabelMouseEntered

    private void Logout_jLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_jLabelMouseExited
        // TODO add your handling code here:
        Logout_jLabel.setBorder(null);
    }//GEN-LAST:event_Logout_jLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Product_Button;
    private javax.swing.JButton Clear_Button;
    private javax.swing.JButton Delete_Product_Button;
    private javax.swing.JButton Edit_Product_Button;
    private javax.swing.JLabel Logout_jLabel;
    private javax.swing.JPanel Logout_jPanel;
    private javax.swing.JTextField Product_InStock_TextField;
    private javax.swing.JTextField Product_Name_TextField;
    private javax.swing.JTextField Product_Price_TextField;
    private javax.swing.JTable Product_table;
    private javax.swing.JLabel Shop_Name_jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
















}
