package com.myproject.project;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.stripe.Stripe;
import java.awt.Desktop;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author user
 */
public class Purchase_product extends javax.swing.JFrame {
    
    public int finalTotal = 0;
    
    public int amount = 0;
    
    public int zero1 = 0;
    public int zero2 = 0;


    /**
     * Creates new form Purchase_product
     */
    public Purchase_product() {
        initComponents();
        
//        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
//        Date d = new Date();
//        String date=dateFormat.format(d);
//
//        
//        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
//        LocalDateTime now = LocalDateTime.now();
//        String time = dtf.format(now);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Product_Name_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Quantity_TextField = new javax.swing.JTextField();
        Add_To_Cart_Button = new javax.swing.JButton();
        Clear_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Card_Payment_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Product_table = new javax.swing.JTable();
        Back_Button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Cart_table = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        Total_Amount_TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Paid_Amount_TextField = new javax.swing.JTextField();
        Return_Amount_TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Product_Price_TextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cash_Payment_jButton = new javax.swing.JButton();
        Delete_From_Cart_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Purchase Product");

        jLabel2.setText("Product Name:");

        Product_Name_TextField.setEditable(false);
        Product_Name_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_Name_TextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantity:");

        Add_To_Cart_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\shopping-cart.png")); // NOI18N
        Add_To_Cart_Button.setText("Add to Cart");
        Add_To_Cart_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_To_Cart_ButtonActionPerformed(evt);
            }
        });

        Clear_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\clear.png")); // NOI18N
        Clear_Button.setText("Clear");
        Clear_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear_ButtonMouseClicked(evt);
            }
        });
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("List of Available Products");

        jLabel5.setText("Shopping Cart");

        Card_Payment_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\credit-card.png")); // NOI18N
        Card_Payment_Button.setText("Pay");
        Card_Payment_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card_Payment_ButtonActionPerformed(evt);
            }
        });

        Product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Product_table);

        Back_Button.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\logout.png")); // NOI18N
        Back_Button.setText("Logout");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        Cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Rate", "Total"
            }
        ));
        Cart_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cart_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Cart_table);

        jLabel6.setText("Total Amount:");

        jLabel7.setText("Paid Amount:");

        Paid_Amount_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Paid_Amount_TextFieldActionPerformed(evt);
            }
        });

        Return_Amount_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Return_Amount_TextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Return Amount:");

        jLabel9.setText("Product Price:");

        Product_Price_TextField.setEditable(false);
        Product_Price_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_Price_TextFieldActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setText("Pay By Cash");

        jLabel11.setText("Pay By Card");

        Cash_Payment_jButton.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\banknotes.png")); // NOI18N
        Cash_Payment_jButton.setText("Pay");
        Cash_Payment_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cash_Payment_jButtonActionPerformed(evt);
            }
        });

        Delete_From_Cart_jButton.setIcon(new javax.swing.ImageIcon("E:\\Project\\4th Sem\\Project I\\Project-I\\Project\\src\\main\\java\\img\\trash.png")); // NOI18N
        Delete_From_Cart_jButton.setText("Delete From Cart");
        Delete_From_Cart_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_From_Cart_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Add_To_Cart_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(Clear_Button))
                            .addComponent(Product_Name_TextField)
                            .addComponent(Quantity_TextField)
                            .addComponent(Product_Price_TextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete_From_Cart_jButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(Total_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(Paid_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Cash_Payment_jButton)
                                        .addComponent(Return_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10))
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Card_Payment_Button)))
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addComponent(jSeparator1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Product_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Product_Price_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Quantity_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add_To_Cart_Button)
                            .addComponent(Clear_Button))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete_From_Cart_jButton)
                            .addComponent(Back_Button))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Total_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Paid_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(Return_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(Cash_Payment_jButton))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(124, 124, 124)
                                .addComponent(Card_Payment_Button))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Product_Name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_Name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_Name_TextFieldActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown

    }//GEN-LAST:event_jPanel1ComponentShown

    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
                try
        {
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT Product_Id,Product_Name,Price,In_Stock FROM products");
            Product_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_formComponentShown

    private void Product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Product_table.getModel();
        int Myindex=Product_table.getSelectedRow();
        Product_Name_TextField.setText(model.getValueAt(Myindex, 1).toString());
        Product_Price_TextField.setText(model.getValueAt(Myindex, 2).toString());
        
    }//GEN-LAST:event_Product_tableMouseClicked

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    private void Clear_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear_ButtonMouseClicked
        // TODO add your handling code here:
        Product_Name_TextField.setText("");
        Product_Price_TextField.setText("");
       Quantity_TextField.setText("");
       
    }//GEN-LAST:event_Clear_ButtonMouseClicked

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        // TODO add your handling code here:
//        setVisible(false);
        dispose();
        new Welcome().setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Cart_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cart_tableMouseClicked
        // TODO add your handling code here:
 
        
        
    }//GEN-LAST:event_Cart_tableMouseClicked

    private void Card_Payment_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card_Payment_ButtonActionPerformed
        // TODO add your handling code here:
        
            amount = Integer.parseInt(Total_Amount_TextField.getText()+String.valueOf(zero1)+String.valueOf(zero2));
            new Server().setAmount(amount);
            
            Server.main(null);
           
           Desktop desk = Desktop.getDesktop();
        try {
            desk.browse(new URI("http://localhost:4242/checkout.html"));
             } catch (URISyntaxException ex) {
            Logger.getLogger(Purchase_product.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Purchase_product.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date d = new Date();
        String date=dateFormat.format(d);

        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH-mm-ss");
        LocalDateTime now = LocalDateTime.now();
        String time = dtf.format(now);
        
        String product_name =Product_Name_TextField.getText();
        String quantity = Quantity_TextField.getText();
        String path = "C:\\Users\\user\\Desktop\\New folder\\Card Payments\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try 
        {
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+date+"_"+time+".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                                  Orchid BCA Shopping Mall \n                                                     Contact no: 123456789");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("\nDate And Time: "+date+" "+time+"\n\n");
            doc.add(paragraph2);
            
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Product_Name");
            tb1.addCell("Quantity");
            tb1.addCell("Rate");
            tb1.addCell("Total");
            
            for(int i=0;i<Cart_table.getRowCount();i++)
            {
                String n = Cart_table.getValueAt(i, 0).toString();
                String q = Cart_table.getValueAt(i, 1).toString();
                String r = Cart_table.getValueAt(i, 2).toString();
                String t = Cart_table.getValueAt(i, 3).toString();
                tb1.addCell(n);
                tb1.addCell(q);
                tb1.addCell(r);
                tb1.addCell(t);
            }
            doc.add(tb1);

            
            Paragraph paragraph3 = new Paragraph("\n\nPaid By Card\nTotal: "+Total_Amount_TextField.getText()+"\n\nThank You For Visiting");
            doc.add(paragraph3);
            JOptionPane.showMessageDialog(null, "BIll Generated");
            this.dispose();
            new Purchase_product().setVisible(true);
         } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
            
        }
        doc.close();
        
//        
//        this.dispose();
//        new Purchase_product().setVisible(true);
       

            
        
    }//GEN-LAST:event_Card_Payment_ButtonActionPerformed

    private void Paid_Amount_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Paid_Amount_TextFieldActionPerformed
        // TODO add your handling code here:
        String paidAmount = Paid_Amount_TextField.getText();
        int z = Integer.parseInt(paidAmount);
        finalTotal = z - finalTotal;
        String finalTotal1 = String.valueOf(finalTotal);
        Return_Amount_TextField.setText(finalTotal1);
        Return_Amount_TextField.setEditable(false);
        
    }//GEN-LAST:event_Paid_Amount_TextFieldActionPerformed

    private void Return_Amount_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_Amount_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Return_Amount_TextFieldActionPerformed

    private void Add_To_Cart_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_To_Cart_ButtonActionPerformed
        // TODO add your handling code here:
        
        if(Product_Name_TextField.getText().isEmpty()||Product_Price_TextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Missing Data");
        }
        else{  
        String productname=Product_Name_TextField.getText();
        DefaultTableModel model = (DefaultTableModel)Cart_table.getModel();
        
        int Myindex=Product_table.getSelectedRow();

        
        
        
        int quantity = Integer.parseInt(Quantity_TextField.getText());
        double rate = Double.parseDouble(Product_Price_TextField.getText());
        int total = (int) (quantity*rate);

        
        
        model.addRow(new Object[]{productname,quantity,rate,total});
        finalTotal=finalTotal+total;
        String finalTotal1 = String.valueOf(finalTotal);
        Total_Amount_TextField.setText(finalTotal1);
                }
    }//GEN-LAST:event_Add_To_Cart_ButtonActionPerformed

    private void Product_Price_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_Price_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_Price_TextFieldActionPerformed

    private void Cash_Payment_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cash_Payment_jButtonActionPerformed
        // TODO add your handling code here:
         Random rand = new Random();
      int upperbound = 999999999;
      int payment_id = rand.nextInt(upperbound); 
      String PaymentType = "Cash";
      
        try {
            Connection con=DatabaseConnection.getCon();
            Statement st=con.createStatement();
            st.execute("INSERT INTO payments(Payment_Id,Payment_Type,Amount) values('"+payment_id+"','"+PaymentType+"','"+Total_Amount_TextField.getText()+"')");
            con.close();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);

        }
        
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date d = new Date();
        String date=dateFormat.format(d);

        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH-mm-ss");
        LocalDateTime now = LocalDateTime.now();
        String time = dtf.format(now);
        
        String product_name =Product_Name_TextField.getText();
        String quantity = Quantity_TextField.getText();
        String path = "C:\\Users\\user\\Desktop\\New folder\\Cash Payments\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try 
        {
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+date+"_"+time+".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                                  Orchid BCA Shopping Mall \n                                                     Contact no: 123456789");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("\nDate And Time: "+date+" "+time+"\n\n");
            doc.add(paragraph2);
            
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Product_Name");
            tb1.addCell("Quantity");
            tb1.addCell("Rate");
            tb1.addCell("Total");
            
            for(int i=0;i<Cart_table.getRowCount();i++)
            {
                String n = Cart_table.getValueAt(i, 0).toString();
                String q = Cart_table.getValueAt(i, 1).toString();
                String r = Cart_table.getValueAt(i, 2).toString();
                String t = Cart_table.getValueAt(i, 3).toString();
                tb1.addCell(n);
                tb1.addCell(q);
                tb1.addCell(r);
                tb1.addCell(t);
            }
            doc.add(tb1);

            
            Paragraph paragraph3 = new Paragraph("\n\nPaid By Cash\nTotal: "+Total_Amount_TextField.getText()+"\nPaid Amount: "+Paid_Amount_TextField.getText()+"\nReturn Amount: "+Return_Amount_TextField.getText()+"\n\nThank You For Visiting");
            doc.add(paragraph3);
            JOptionPane.showMessageDialog(null, "BIll Generated");
            this.dispose();
            new Purchase_product().setVisible(true);
         } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
            
        }
        doc.close();
        
    }//GEN-LAST:event_Cash_Payment_jButtonActionPerformed

    private void Delete_From_Cart_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_From_Cart_jButtonActionPerformed
        // TODO add your handling code here:
        String productname=Product_Name_TextField.getText();
        DefaultTableModel model = (DefaultTableModel)Cart_table.getModel();
        int Myindex=Cart_table.getSelectedRow();
        
        
        
 
        int quantity = Integer.parseInt(Quantity_TextField.getText());
        int total = Integer.parseInt(model.getValueAt(Myindex, 3).toString());
        finalTotal = Integer.parseInt(Total_Amount_TextField.getText());
        
      finalTotal=finalTotal-total;
      String newfinalTotal1 = String.valueOf(finalTotal);
      Total_Amount_TextField.setText(newfinalTotal1);
      model.removeRow(Myindex);

    }//GEN-LAST:event_Delete_From_Cart_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_To_Cart_Button;
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Card_Payment_Button;
    private javax.swing.JTable Cart_table;
    private javax.swing.JButton Cash_Payment_jButton;
    private javax.swing.JButton Clear_Button;
    private javax.swing.JButton Delete_From_Cart_jButton;
    private javax.swing.JTextField Paid_Amount_TextField;
    private javax.swing.JTextField Product_Name_TextField;
    private javax.swing.JTextField Product_Price_TextField;
    private javax.swing.JTable Product_table;
    private javax.swing.JTextField Quantity_TextField;
    private javax.swing.JTextField Return_Amount_TextField;
    private javax.swing.JTextField Total_Amount_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
